### ISSUE TITLE
Readme JSON isn't valid.

### ISSUE THREAD

**Issue by tankerkiller125** [ddsky/unibox#2]
Please update the json in the readme to valid JSON. It is impossible to use the json_decode function in PHP on it to get a basic array example and if the JSON really is read in that format by the lib then there is no easy way to take MySQL results and output them in that format.

Taking the direct json example and making it valid out puts it as such:

```
{
    "words": [
        {
            "name": "name",
            "image": "http://..."
        }
    ],
    "suggests": {
        "headline 1": [
            {
                "name": "name",
                "image": "http://...",
                "link": "http://..."
            }
        ]
    }
}
```

**Comment by tankerkiller125** [comment]
I might also add that the closest I was able to get using PHP was as follows:

```
{
    "words": {
        "name": "test",
        "image": "http://..."
    },
    "suggests": {
        "Example": {
            "name": "Example",
            "link": "http://example.com"
        }
    }
}
```

**Comment by tankerkiller125** [comment]
Also want to add that I can't get it to work because a function called key.replace doesn't exist (line 157)

**Comment by ddsky** [comment]
Thanks, I'll look into that problem asap!

**Comment by ddsky** [comment]
Fixed the json formatting. I could not reproduce the other issue with key.replace on line 157. My guess would be that you deliver a wrong format of suggests from the server so that "key" is undefined. Take a look at the json format for suggests. "headline 1" is a sample key there. Does that help?

**Comment by tankerkiller125** [comment]
Its very odd for me... Using Jquery 2.whateverisnew and bare HTML with the CSS provided... And I am litteraly using the same JSON as in the new read me.

**Comment by ddsky** [comment]
odd indeed. Well if it works for you without line 157, that's cool then. Also, if you built something nice and want me to share a screenshot of the implementation and a link in the readme, just let me know ;)

**Comment by tankerkiller125** [comment]
I might want to note that the Readme JSON still isn't valid... Unfortantly JSON is very picky and requires double quotes. You can check JSON using http://jsonlint.com

**Comment by ddsky** [comment]
yup thanks, changed
